### PR TITLE
Added drum-kit project

### LINKED ISSUE #4: Showcase your HTML, CSS and JavaScript Projects.

### PR DESCRIPTION
**Pull request by prnvtripathi**
Simple project using JS -> animations & sounds using JS
resolve #4

### CODE REVIEW

**Comment by Mridul2820** [comment]
Hi @prnvtripathi  your website looks amazing.

Can you add your details in the `README.md` in the JS section?
Like This

```bash
| Drum kit | [Demo](Demo Link) | [Source Code](/projects/javascript/Drum-Set) | [prnvtripathi](https://github.com/prnvtripathi)|
```

Thank you for contributing! 🚀

**Comment by prnvtripathi** [comment]
Please check @Mridul2820  and see if I can do anything else

**Comment by Mridul2820** [comment]
Add this in the main `README.md` file

```
| Drum kit | [Demo](https://prnvtripathi.github.io/drum-kit/) | [Source Code](/projects/javascript/Drum-Set) | by [Pranav Tripathi](https://github.com/prnvtripathi) |
```
And Remove it from the `projects/javascript/README.md` file

**Comment by prnvtripathi** [comment]
Sorry for that error, i think it's resolved now @Mridul2820

**Review by Mridul2820 — APPROVED** [review]

**Comment by Mridul2820** [comment]
Thank you for contributing! 🚀

**Pull request merged**
