### PR TITLE
Simple Typing Game

### PR DESCRIPTION
**Pull request by ayushpandey830**
Simple Typing Game using HTML, CSS and JS.

### CODE REVIEW

**Comment by Mridul2820** [comment]
Hi @ayushpandey830 , You need to add your project details in the main `README.md` File

You can follow this Example: [example-readme-details](https://github.com/Mridul2820/Hacktoberfest2022/blob/master/CONTRIBUTING.md#example-readme-details)

**Comment by ayushpandey830** [comment]
> Hi @ayushpandey830 , You need to add your project details in the main `README.md` File
> 
> You can follow this Example: [example-readme-details](https://github.com/Mridul2820/Hacktoberfest2022/blob/master/CONTRIBUTING.md#example-readme-details)

Done!!

**Comment by Mridul2820** [comment]
You need to add that on this same PR

**Comment by ayushpandey830** [comment]
Did the changes. Thanks for explaining :)

**Review by Mridul2820 — APPROVED** [review]

**Comment by Mridul2820** [comment]
Thank you for contributing! 🚀

**Pull request merged**
